service: fastapi-lambda

provider:
  name: aws
  runtime: python3.8
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dv'}  

functions:
  api:
    image:
      uri: ${env:AWS_ACCOUNT_ID}.dkr.ecr.${env:AWS_REGION}.amazonaws.com/fastapi-lambda:latest
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /items/{item_id}
          method: get
