service: fastapi-lambda

provider:
  name: aws
  runtime: python3.8
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dv'}
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024
    apiKeys:
      - name: test-key

functions:
  api:
    image:
      uri: ${env:AWS_ACCOUNT_ID}.dkr.ecr.${env:AWS_REGION}.amazonaws.com/fastapi-lambda:latest
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /{proxy+}
          method: get
      - http:
          path: /items/{item_id}
          method: get
          private: true
